<!DOCTYPE html>
<html lang="en">

<head>
<title> Portfolio for Chelsea Reese </title>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link rel="stylesheet" type="text/css" href="./assets/css/style.css" />
</head>
<body>
    <header>
    <h1>Chelsea Reese</h1>
    <nav>
        <ul>
             <li>
                <a href="#Work">Work</a>
             </li>
            <li>
                 <a href="#About-me">About Me</a>
            </li>
            <li>
                <a href="#Contact-me">Contact Me</a>
        </li>
     </ul>
    </nav>
    </header>
    <section id="Work">
        <h2>Work</h2>
            <img class="filler-image" src="./assets/images/IMG_2765.JPG" alt="filler" href= x/>
            <img class="filler-image" src="./assets/images/IMG_5011.JPG" alt="filler" href= x/>
            <img class="filler-image" src="./assets/images/IMG_5012.JPG" alt="filler" href= x/>
    </section>
    <section id="About-me">
        <h3>About Me</h3>
        <img class="self-image" src="./assets/images/9479E04E-7AA8-41FE-A06C-390C3415A08C.jpg" alt="Image of Me" />
            <p> I am 21 years old and work full time in customer service. I have been working customer
            service positions since I graduated high school and while it is something I appreciate
            having been trained in, I am ready for the next step in my life.
            </p>
    </section>
     <footer id="Contact-me">
        <h3>Contact Me</h3>
            <ul>
                <li>Phone: 801-505-8647</li>
                <li>Email: chelsea.reese@icloud.com</li>
                <li>LinkedIn: <a href="https://www.linkedin.com/in/chelsea-reese-58805a20b/">Chelsea Reese</a> </li>
            </ul>
    </footer>
</body>
</html>
